vars

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -11,7 +11,7 @@ on:
         required: true
       DOCKER_PASSWORD:
         required: true
-      ARGOCD_AUTH_TOKEN:
+      ARGOCD_PASSWORD:
         required: true
       ARGOCD_SERVER:
         required: true
@@ -86,19 +86,51 @@ jobs:
           git commit -m "chore: update image tag to ${IMAGE_TAG}" || echo "No changes to commit"
           git push
 
+
   argocd_sync:
     runs-on: ubuntu-latest
     needs: docker_build
     env:
       CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
       REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
+      ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
+      ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
+      ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
 
     steps:
-      - name: Sync ArgoCD app
+      - name: Install ArgoCD CLI
+        run: |
+          curl -sSL -o /usr/local/bin/argocd https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64
+          chmod +x /usr/local/bin/argocd
+
+      - name: Login to ArgoCD
+        run: |
+          argocd login "${{ secrets.ARGOCD_SERVER }}" \
+            --username "admin" \
+            --password "${{ secrets.ARGOCD_PASSWORD }}" \
+            --grpc-web \
+            --insecure
+      - name: Check if ArgoCD app exists
         run: |
           TARGET_APP="${REPO_SLUG}-${CI_ENVIRONMENT_NAME}"
-          echo "Syncing $TARGET_APP"
-          argocd app sync "$TARGET_APP" \
-            --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} \
-            --server ${{ secrets.ARGOCD_SERVER }} \
-            --insecure
+          if ! argocd app get "$TARGET_APP" > /dev/null 2>&1; then
+            echo "ERROR: ArgoCD app $TARGET_APP does not exist"
+            exit 1
+          fi
+
+#  argocd_sync:
+#     runs-on: ubuntu-latest
+#     needs: docker_build
+#     env:
+#       CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
+#       REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
+
+#     steps:
+#       - name: Sync ArgoCD app
+#         run: |
+#           TARGET_APP="${REPO_SLUG}-${CI_ENVIRONMENT_NAME}"
+#           echo "Syncing $TARGET_APP"
+#           argocd app sync "$TARGET_APP" \
+#             --auth-token ${{ secrets.ARGOCD_AUTH_TOKEN }} \
+#             --server ${{ secrets.ARGOCD_SERVER }} \
+#             --insecure
