image with tag

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -44,15 +44,20 @@ jobs:
           REPO_SLUG=$(echo "$REPO_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9-]/-/g')
           REPO_SLUG=${REPO_SLUG#wayagram-}
 
+          FULL_IMAGE_WITH_TAG="${FULL_IMAGE_NAME}:${TAG}"
+
           echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
           echo "REPO_SLUG=${REPO_SLUG}" >> $GITHUB_ENV
           echo "BRANCH_NAME=${BRANCH_NAME}" >> $GITHUB_ENV
           echo "FULL_IMAGE_NAME=${FULL_IMAGE_NAME}" >> $GITHUB_ENV
           echo "TAG=${TAG}" >> $GITHUB_ENV
+          echo "FULL_IMAGE_WITH_TAG=${FULL_IMAGE_WITH_TAG}" >> $GITHUB_ENV
 
           echo "tag=${TAG}" >> $GITHUB_OUTPUT
           echo "image_repo=${FULL_IMAGE_NAME}" >> $GITHUB_OUTPUT
           echo "slug=${REPO_SLUG}" >> $GITHUB_OUTPUT
+          echo "full_image=${FULL_IMAGE_WITH_TAG}" >> $GITHUB_OUTPUT
+
 
       - name: Log in to DockerHub
         run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
@@ -69,23 +74,23 @@ jobs:
       CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
       IMAGE_REPO: ${{ needs.docker_build.outputs.image_repo }}
       REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
-      TAG: ${{ needs.docker_build.outputs.tag }}
+      FULL_IMAGE_WITH_TAG: ${{ needs.docker_build.outputs.full_image }}
       GITHUB_PAT: ${{ secrets.WAYA_HELM_PAT }}
 
     steps:
       - name: Checkout this repo
         uses: actions/checkout@v3
 
-      - name: Clone waya-helm-charts repo
+      - name: Clone waya-helm-charts repo and update values
         run: |
           git clone https://kayodewaya:${GITHUB_PAT}@github.com/WAYA-MULTI-LINK/waya-helm-charts.git
           cd waya-helm-charts
 
           FILE_PATH="./helm/microservices/${REPO_SLUG}/${CI_ENVIRONMENT_NAME}-values.yaml"
-          echo "Updating $FILE_PATH with new image.repository: ${TAG}"
+          echo "Updating $FILE_PATH with new image.repository: ${FULL_IMAGE_WITH_TAG}"
 
-          if [ -z "${TAG}" ]; then
-            echo "TAG is empty. Failing the job."
+          if [ -z "${FULL_IMAGE_WITH_TAG}" ]; then
+            echo "FULL_IMAGE_WITH_TAG is empty. Failing the job."
             exit 1
           fi
 
@@ -94,20 +99,26 @@ jobs:
             exit 1
           fi
 
-          # Correct yq syntax
-          yq eval -i ".image.repository = \"${TAG}\"" "$FILE_PATH"
+          yq eval -i ".image.repository = \"${FULL_IMAGE_WITH_TAG}\"" "$FILE_PATH"
 
           git config --global user.email "github-actions@github.com"
           git config --global user.name "github-actions"
 
           git add "$FILE_PATH"
-          git commit -m "chore: update image.repository to ${TAG}" || echo "No changes to commit"
+          git commit -m "chore: update image.repository to ${FULL_IMAGE_WITH_TAG}" || echo "No changes to commit"
           git push origin main
+
 
 
   argocd_sync:
     runs-on: ubuntu-latest
     needs: [docker_build]
+    # env:
+    #   CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
+    #   REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
+    #   ARGOCD_SERVER: ${{ secrets.ARGOCD_SERVER }}
+    #   ARGOCD_USERNAME: ${{ secrets.ARGOCD_USERNAME }}
+    #   ARGOCD_PASSWORD: ${{ secrets.ARGOCD_PASSWORD }}
     env:
       CI_ENVIRONMENT_NAME: ${{ inputs.CI_ENVIRONMENT_NAME }}
       REPO_SLUG: ${{ needs.docker_build.outputs.slug }}
@@ -119,10 +130,11 @@ jobs:
           chmod +x /usr/local/bin/argocd
 
       - name: Login to ArgoCD
-        run: argocd login ${{ secrets.ARGOCD_SERVER }} --username admin --password ${{ secrets.ARGOCD_PASSWORD }} --grpc-web --insecure
+        run: argocd login argocd.dev.wayalinks.com --username admin --password WqUNi85pNUJ43A3q --grpc-web --insecure 
 
       - name: Check if ArgoCD app exists
         run: |
+          echo "${REPO_SLUG}"
           TARGET_APP="${REPO_SLUG}-${CI_ENVIRONMENT_NAME}"
           echo "Checking ArgoCD app: $TARGET_APP"
           if ! argocd app get "$TARGET_APP" > /dev/null 2>&1; then
